# Generated by Django 5.1.2 on 2024-11-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
